# based on: https://github.com/andry81/github-accum-stats
#

name: "github-accum-stats: GitHub clones counter for 14 days at every 8 hours and clones accumulator"

on:
  schedule:
    - cron: "0 */8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  accum-gh-clone-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: mrfoxie/gh-action--accum-gh-stats@master
        with:
          deps_repo_owner:          mrfoxie

          stat_repo_owner:          mrfoxie
          stat_repo:                github-accum-stats
          stat_entity_path:         traffic/clones
          stat_repo_read_token:     ${{ secrets.GITHUB_TOKEN }}
          stats_list_key:           clones

          curl_flags: >-
            -H 'Cache-Control: no-cache'

          output_repo_owner:        andry81
          output_repo:              github-accum-stats--gh-stats
          output_repo_branch:       master
          output_repo_dir:          traffic/clones
          # NOTE: You should use something like `secrets.WRITE_STATS_TOKEN` if the input and the output repository has different owners.
          output_repo_write_token:  ${{ secrets.GITHUB_TOKEN }}
